# BlockVault

# Vault settings
vault:
  start-time: null
  started: false
  region:
    upperregion:
      X: -138
      Y: 97
      Z: 118
    lowerregion:
      X: 133
      Y: 68
      Z: 96
  excludeditems:
    - debug_stick
    - structure_block
    - barrier
    - command_block
    - chain_command_block
    - repeating_command_block
    - light
    - jigsaw
    - knowledge_book
    - spawner
    - end_portal_frame
    - frosted_ice
    - bedrock
    - dragon_egg
    - piglin_brute_spawn_egg
    - parrot_spawn_egg
    - turtle_spawn_egg
    - zombie_spawn_egg
    - mule_spawn_egg
    - armadillo_spawn_egg
    - tropical_fish_spawn_egg
    - blaze_spawn_egg
    - shulker_spawn_egg
    - sniffer_spawn_egg
    - polar_bear_spawn_egg
    - phantom_spawn_egg
    - guardian_spawn_egg
    - ravager_spawn_egg
    - wandering_trader_spawn_egg
    - villager_spawn_egg
    - wither_skeleton_spawn_egg
    - warden_spawn_egg
    - ender_dragon_spawn_egg
    - bat_spawn_egg
    - sniffer_egg
    - camel_spawn_egg
    - creeper_spawn_egg
    - breeze_spawn_egg
    - iron_golem_spawn_egg

timer:
  enabled: false
  timer-end: null

# Points system settings
points:
  common: 1
  uncommon: 5
  rare: 10

# Language settings
lang:
  prefix: "&8&l[&3BD&8&l]"