# BlockVault Configuration
# Configures the BlockVault, collection goals, progress tracking, and rewards system.

# Vault settings
vault:
  start-time: "2025-01-01 14:30:00"
  started: false
  location:
    # Coordinates for the vault's center point
    x: 100
    y: 64
    z: 100
    world: world

timer:
  enabled: false
  timer-end: "2025-01-01 14:30:00"

# Points system settings
points:
  common: 1
  uncommon: 5
  rare: 10

# Language settings
lang:
  prefix: "&8&l[&3BD&8&l]"