# BlockVault Configuration
# Configures the BlockVault, collection goals, progress tracking, and rewards system.

# Vault settings
vault:
  location:
    # Coordinates for the vault's center point
    x: 100
    y: 64
    z: 100
    world: world

  # Schematic settings for the vault design
  schematic:
    # Path to the schematic file
    path: "vault.schem"

# Points system settings
points:
  # Base points for each block type
  base_points:
    common: 1 # Points for common blocks (e.g., Cobblestone, Oak Logs)
    uncommon: 5 # Points for uncommon blocks (e.g., Prismarine, Obsidian)
    rare: 10 # Points for rare blocks/items (e.g., Dragon Egg, Netherite Block)

# Language settings
lang:
  prefix: "&8&l[&3BD&8&l]"