name: BlockVault
version: '1.0.0'
main: me.benrobson.blockvault.BlockVault
api-version: '1.21'
softdepend: [WorldEdit]
commands:
  bvadd:
    description: Command
    usage: /bvadd <itemblock>
  bvgenerate:
    description: Command
    usage: /bvgenerate
  bvleaderboard:
    description: Command
    usage: /bvleaderboard
  bvprogress:
    description: Command
    usage: /bvprogress
  bvstart:
    description: Command
    usage: /bvstart
